num1=float(input("Enter the first number"))
num2=float(input("Enter the second number"))
print("Addition: \t",num1+num2)
print("Subtraction: \t",num1-num2)
print("Multiplication: \t",num1*num2)
print("Division: \t",num1/num2)